### ISSUE TITLE
button stopped working this week

### ISSUE THREAD

**Issue by ihstiv** [nickbeeton/garminstuff#5]
When I click the button to copy ebike segments absolutely nothing happens and I get the below error in console.  Same result using Chrome, Opera, and Firefox on Windows 10.

I have had great success using it for a few weeks, thank you so much for creating it!

Let me know if I can provide more info/etc.

window.f started
`userscript.html?id=9b78eda5-9975-449b-bf22-8adeb24bc90d:41 Uncaught (in promise) TypeError: Cannot read property '0' of null
    at window.f (userscript.html?id=9b78eda5-9975-449b-bf22-8adeb24bc90d:41)
    at HTMLButtonElement.window.f1 (userscript.html?id=9b78eda5-9975-449b-bf22-8adeb24bc90d:398)`

**Comment by happybear88** [comment]
I confirm the issue on latest Chrome and Edge Dev.

The first item (at window.f) takes to 
`window.namesorig[i-1] = window.stufforig[i].match(/\"name\":\"[^\"]+/g)[0].replace("\"name\":\"","")`
The second item (at HTMLButtonElement.window.f1) takes to
`window.f2 = function(){
    window.f(true, window.g);`

**Comment by nickbeeton** [comment]
Thanks all for the report - I'm snowed under with work at the moment (and self-isolating with a 3 year old!) so I'll look into this after things settle down!

**Comment by nickbeeton** [comment]
Ok it looks like it was a simple indexing issue, presumably Strava tweaked its web code and the assumptions my code made suddenly became wrong 😆 

I *think* I've fixed this now (Version 0.6.4) but please test it yourselves and let me know - I'll leave this issue open till then, as I'm not 100% confident!

**Comment by happybear88** [comment]
Hello @nickbeeton! I confirm the fix, thank you very much!

**Comment by nickbeeton** [comment]
Oh good! I'm sure now Strava's changing its whole model everything will break again soon enough 🙄 but until then I'm glad it's working 😊
