### ISSUE TITLE
button

### ISSUE THREAD

**Issue by Duese911** [nickbeeton/garminstuff#6]
i don't see the button.
where should this be?

**Comment by MrBurnsDev** [comment]
You have to install tamper monkey. Then the button will be on whatever browser you install it on at the top toolbar.

**Comment by MrBurnsDev** [comment]
I ran processed last night and they worked great on chrome.

**Comment by Duese911** [comment]
Tamper Monkey is Installt. The script is also recognized, but nothing happens in Strava.
I dont see a butten to coppy the segment

**Comment by MrBurnsDev** [comment]
Have you turned your activity tape on to the bike ride? If so you should see two new orange buttons  that basically say run script as a public segment or as a private. Check your Activity type.

**Comment by MrBurnsDev** [comment]
Type... Not tape

**Comment by Duese911** [comment]
It works now. I had to put chrome in English and then the buttons are visible. The Activity type was eBike

**Comment by nickbeeton** [comment]
Ah yes, I forgot about the browser needing to be in English issue sorry... I'll have to add that to the checklist! Glad it's working for you at least!
