### ISSUE TITLE
script hangs after converting from ebike ride to ride

### ISSUE THREAD

**Issue by ihstiv** [nickbeeton/garminstuff#7]
subject pretty much says it, when i click 'copy to public ebike segments' button in chrome, it opens a new tab and converts the ride from ebike ride to 'ride' and then nothing else happens.

Chrome Version 83.0.4103.106 (Official Build) (64-bit)

Only errors I see in console are related to x-domain stuff for the fonts and twitter..

**Comment by ihstiv** [comment]
I discovered that chrome started blocking popups and that is what caused the issue. Seems to be working as desired now that I've unblocked popups in chrome for strava.

**Comment by nickbeeton** [comment]
Hi @ihstiv, just curious - where did you find out about this script? I'll go back to the forum posts I remember making about it and modify the posts to say that you need to unblock popups because I've had a few people with this issue and another (Chrome needs to be in English).

**Comment by ihstiv** [comment]
Hi @nickbeeton 
Here's the thread where I found your script:
https://www.emtbforums.com/community/threads/strava-segments-how-to-copy-non-ebike-segments.1084/

Cheers
Steve
